### ISSUE TITLE
Docker Permission Issues

### ISSUE THREAD

**Issue by straussmaximilian** [MannLabs/CKG#28]
**Describe the bug**
Hi, I tried to explore the docker installation a bit more. I noticed when clicking on the sample projects, I get permission denied errors. Also when trying to upload data to a self-created project the options are grayed out. 

**To Reproduce**
1. Go to `Home` -> `Available Projects` 
2. Click on any of them (e.g. NON-ALCHOLIC FATTY LIVER DISEASE)
3. Page reloads but nothing happens, terminal shows permission denied (Screenshot 1)
---
1. Go to `Home` -> `DATA UPLOAD` 
2. Type project identifier
3. All options are greyed out 

Note that it correctly throws an error if the project name is not found.

**Screenshots**
![Screen Shot 2020-07-16 at 12 19 42](https://user-images.githubusercontent.com/16521288/87660203-fc2ecc00-c75e-11ea-9170-011f6704e449.png)

![Screen Shot 2020-07-16 at 12 20 08](https://user-images.githubusercontent.com/16521288/87660195-f933db80-c75e-11ea-8c06-f836af60ee5f.png)

**Comment by Stanley80** [comment]
Hello straussmaximilian,
I had the same issue how did you solve it?

Thank you very much

**Comment by albsantosdel** [comment]
Dear @Stanley80
Are you also getting the 'Permission denied' error?
If you are using the CKG's Docker container, we have seen this type of error before and I am currently working on a newer version that should solve these issues. I can update you once it is ready.

However, if instead you have your own installation and you experience that you cannot upload data, that might be because you are using an incorrect Project identifier. The field 'Project identifier' in the Data Upload page expects an identifier generated by the graph, which looks something like '_P0000001_' .  If you have not created a project yet, you can start creating one in the 'Project creation' page which will provide you with a valid identifier.

**Comment by straussmaximilian** [comment]
@Stanley80 
I didn't manage to solve this yet, so I think @albsantosdel's update will be the best bet.

**Comment by Stanley80** [comment]
Thank you for your responses!!!
I am using a docker container. I temporarily solve by  RUN sudo chmod 777 /CKG -R  in the docker file.

Issue seems to be raised by absence of permission of nginx user on the CKG/data folder created on docker run time.

Hope this can help

**Comment by Stanley80** [comment]
Hello everybody!!!!
I have some news about permission denied in my docker installation.
Every time I upload a file in CKG it creates a new subfolder in the /CKG/data folder with not writable permissions by default.

This raises the permission denied problem.

Running the command 

umask 000 

in the docker shell seems to solve the issue.

I'll keep you warned about the solution

**Comment by albsantosdel** [comment]
These issue was solve in version 1.0: commit 057fbbf786e8655dc552cf42ed8fe788adb92f2f
