### ISSUE TITLE
Samples not being processed

### ISSUE THREAD

**Issue by nickhsmith** [MannLabs/CKG#34]
I am working with a dataset that is derived from 2 groups totaling 52 samples (36, and 16 respectively) however in the proteomics analysis results. Only 27 samples are processed.

I imagine that the other samples don't meet the default 30% protein cutoff or some other cutoff value, but it is impossible for me to investigate as the samples have been renamed from the ClinicalData and ExperimentalDesign values to something along the lines of `AS148` `AS97` ...

Is there a reason my samples are being renamed, is there a dictionary or key that will allow me to identify which samples are being processed and which are not?

Thank you again.

**Comment by albsantosdel** [comment]
Dear Nick, 
Thank you for raising this issue. We were actually showing internal identifiers because that works if the whole project uses those identifiers from the beginning. That's not always the case (actually quite the opposite) so we are changing that in the next release. I have just pushed a new branch with additional features and also showing the right identifiers [feature_addition](https://github.com/MannLabs/CKG/tree/feature_addition). If you want you can already test this version or otherwise we will soon release it as an upgraded CKG version. If you want to test it, you will need to run in your virtual environment:
`pip3 install --ignore-installed -r clean_requirements.txt` 

clean_requirements.txt is a reduced list of libraries required which will reduce future conflicts with pinned versions.

Also, this new version changes a little bit the format of the experimental design file: columns _grouping1_ and _grouping2_ need to be added to the Experimental_design file (before they were in the Clinical_data).

After this, upload the data for your project again.
Let me know how it goes.

**Comment by albsantosdel** [comment]
I am closing this pull request _for now_ because of inactivity and outdated code.
@nickhsmith  we can always reopen it though! :)
